# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23a4589c56b3d3090151e97a557ecf8542039c59eaa7e056b1a21f0f1718e4ca2523d83f128d001a7468c48e36085860558b00cf7cff63565e47dc4566c9c59e

test:
  secret_key_base: afd7dcd4d41fff2ffc57402918fb44acc583a79d1dbb8a8a38f5de5f41f23c3ab59ac523d871e7af4e62b25a704662d22d04adb29d5e4fa15f244b6468ffd844

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
